### ISSUE TITLE
备忘录

### ISSUE THREAD

**Issue by mecoepcoo** [mecoepcoo/react-ts-boilerplate#1]
# 背景
使用[CRA](https://github.com/facebook/create-react-app)新建项目，发现自定义程度不够，又找到[react-app-rewired](https://github.com/timarney/react-app-rewired)和[customize-cra](https://github.com/arackaf/customize-cra)，尝试觉得使用异常繁琐，且会消耗额外的维护精力，遂有此构想。
# 要做的事
- [x] git规范支持 #19 
- [x] `webpack` 的基本配置（jsx，tree shaking，es支持等） #2 
- [x] `typescript` 支持 #3 
- [x] 代码压缩 #4
- [x] css 模块化 #5
- [x] `less sass stylus` 等样式预处理器支持 #6
- [x] 自动增加 css 前缀 #7
- [x] eslint/tslint和prettier支持 #18
- [x] `code spliting` 缩小单个文件体积，加快首屏渲染 #8
- [x] `chunk` 提取公共代码 #9
- [x] `preload` 预加载资源，`prefetch` 按需请求资源 #10
- [x] ~~`prerender` 加快首屏渲染速度 #11~~
- [x] `dns-prefetch` 加快首屏渲染 #12
- [x] 懒加载，按需加载 #13
- [x] 自定义的多环境 `环境变量` #15
- [x] 小图片 `base64` 处理 #14
- [x] 支持jest测试 #17
- [x] 加快编译速度 #16
